# -*- coding: utf-8 -*-
"""Data Exploration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11RADRfJSmcvkYlRiYkr4qLeEjR3VsCvU
"""

df = pd.read_csv('/content/drive/MyDrive/salaries_by_college_major.csv')

df.head()

clean_df = df.dropna()

clean_df.tail()

clean_df['Starting Median Salary']

clean_df['Starting Median Salary'].idxmax()

clean_df['Undergraduate Major'].loc[43]

clean_df.loc[43]

clean_df['Mid-Career Median Salary'].idxmax()

clean_df['Undergraduate Major'][8]

clean_df['Starting Median Salary'].loc[8]

clean_df['Starting Median Salary'].idxmin()

clean_df['Undergraduate Major'][49]

clean_df['Starting Median Salary'].idxmin()

clean_df['Starting Median Salary'][49]

clean_df.loc[clean_df['Mid-Career Median Salary'].idxmin()]

clean_df.loc[clean_df['Mid-Career Median Salary'].idxmin()]['Undergraduate Major']

print(clean_df.loc[clean_df['Mid-Career Median Salary'].idxmin()]['Undergraduate Major'])

spread_col = clean_df['Mid-Career 90th Percentile Salary'].subtract(clean_df['Mid-Career 10th Percentile Salary'])

spread_col

clean_df.insert(6, 'Spread Risk', spread_col)

clean_df.head()

low_risk = clean_df.sort_values('Spread Risk')

low_risk[['Undergraduate Major', 'Spread Risk']].head()

high_potential = clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False).head()

high_potential

high_potential[['Undergraduate Major','Mid-Career Median Salary']]

highest_spread = clean_df.sort_values('Mid-Career Median Salary', ascending=False)

highest_spread[['Undergraduate Major', 'Spread Risk']].head()

clean_df.groupby('Group').count()

clean_df.groupby('Group').mean()

pd.options.display.float_format = '{:,.2f}'.format

clean_df.groupby('Group').head()

numeric_columns = ['Starting Median Salary', 'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary', 'Mid-Career 90th Percentile Salary', 'Spread Risk']  # Define numeric_columns

clean_df.groupby('Group')[numeric_columns].mean()

