"""added tmdb id

Revision ID: 334ec0b306bd
Revises: 64965ab02532
Create Date: 2025-01-16 18:08:18.087244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334ec0b306bd'
down_revision = '64965ab02532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_tmdb_id', ['tmdb_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('tmdb_id')

    # ### end Alembic commands ###
