"""Made columns nullable

Revision ID: 64965ab02532
Revises: 
Create Date: 2025-01-16 17:12:56.034729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64965ab02532'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('rating',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('ranking',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('img_url',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('img_url',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('ranking',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rating',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
